---
- hosts: all
  become: true
  gather_facts: false
  tasks:
    - name: update apt cache
      apt:   cache_valid_time=6000

- include: control.yml
- include: database.yml
- include: webserver.yml
- include: loadbalancer.yml